feat(block witness):finish adding and update tests
Bytom/bytom pull request #1906
Opened 2021-04-20 04:16 UTC by mingjingc

2021-04-20 07:05 UTC, hauson commented on protocol/bc/types/block_header.go
>  	return nil
最后这个不用判断err!=nil 
可以直接 return   err

2021-04-20 07:05 UTC, hauson commented on protocol/bc/types/block_witness_test.go
> +		},
老板， 一个小建议，给测试案例加一下描述Desc，方便知道这个测试案例的作用。

2021-04-20 13:56 UTC, Paladz commented on protocol/bc/types/block_header_test.go
> +				BlockWitness: BlockWitness{0xbe, 0xef},
兄弟。。。。来一个正常签名长度的例子吧？

2021-04-21 02:14 UTC, hauson commented on protocol/bc/types/block_header.go
> +	if _, err = blockchain.ReadExtensibleString(r, bh.BlockWitness.readFrom); err != nil {
> 我想可以考虑，提交一个新pr，统一修改代码style问题，这样代码审核者也会舒服，你觉得呢？

前人的代码，看到了不遵守现在规范的，可改可不该，看自己的时间了。
自己写的代码或修改过后的代码，要遵守现在的空行规范了。

2021-04-21 02:21 UTC, hauson commented on protocol/bc/types/block_witness_test.go
> +		},
> 好主意。不过这里我感觉这个测试用例比较简单，看方法名应该可以看懂，所以索性不加。你觉得这个测试用例哪里需要加注释？

1.  这几个测试案例长的都差不对， 写上描述，其他老板在做review时，还能帮着审下逻辑。
2. 每个测试案例都是在测不同的方向，现在这个情况，都看不出是否存在冗余的测试案例。
3. 以后代码有改动，其中某个测试案例错了， 有描述还能快速的定位岀是那个测试案例错了。

2021-04-21 02:22 UTC, hauson commented on protocol/bc/types/block_header.go
>  	return nil
> 谢谢提醒。不过这个属于代码style改变，新提交pr统一修改会不会更好？

 现在的写法多了几行代码。 可读性不变的情况下，代码越少越好。

2021-04-21 02:23 UTC, mingjingc commented on protocol/bc/types/block_header.go
> +	if _, err = blockchain.ReadExtensibleString(r, bh.BlockWitness.readFrom); err != nil {
知道了，谢谢你。

2021-04-21 02:23 UTC, jacksoom commented on protocol/bc/types/block_witness_test.go
> +		},
> 好主意。不过这里我感觉这个测试用例比较简单，看方法名应该可以看懂，所以索性不加。你觉得这个测试用例哪里需要加注释？

不管简单与否，也最好加一个desc

2021-04-21 02:47 UTC, mingjingc commented on protocol/bc/types/block_header.go
>  	return nil
这个有error变量，可否省略所有返回参数呢

2021-04-21 02:54 UTC, mingjingc commented on protocol/bc/types/block_witness_test.go
> +		},
加啦~

2021-04-21 02:54 UTC, mingjingc commented on protocol/bc/types/block_witness_test.go
> +		},
加啦~

2021-04-21 02:57 UTC, mingjingc commented on protocol/bc/types/block_header.go
> +	if _, err = blockchain.WriteExtensibleString(w, nil, bh.BlockWitness.writeTo); err != nil {
都空了

2021-04-21 03:03 UTC, jacksoom commented on protocol/bc/types/block_witness_test.go
> +		},
> 加啦~

https://github.com/Bytom/bytom/pull/1874/files   建议参考一下这里面的写法

2021-04-21 03:03 UTC, jacksoom requested changes
https://github.com/Bytom/bytom/pull/1874/files 建议参考一下这里面的写法

2021-04-21 03:06 UTC, mingjingc commented on protocol/bc/types/block_header.go
> +	if _, err = blockchain.ReadExtensibleString(r, bh.BlockWitness.readFrom); err != nil {
已修改

2021-04-21 03:06 UTC, mingjingc commented on protocol/bc/types/block_header.go
> +	if _, err = blockchain.WriteExtensibleString(w, nil, bh.BlockWitness.writeTo); err != nil {
已修改

2021-04-21 03:06 UTC, mingjingc commented on protocol/bc/types/block_witness_test.go
> +		},
已修改

2021-04-21 03:10 UTC, hauson approved these changes

2021-04-21 03:21 UTC, Paladz submitted a review, later dismissed

2021-04-21 03:51 UTC, jacksoom submitted a review, later dismissed

2021-04-21 06:41 UTC, jacksoom approved these changes

2021-04-21 06:45 UTC, Paladz approved these changes

2021-04-21 06:46 UTC, merged